import requests
import os
import base64
from message_bus import get_messages, create_message, send_message
from llm import call_llm

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
REPO = "JHiba/launchmind-rh"

HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

class EngineerAgent:

    def run(self):
        messages = get_messages("engineer")
        for msg in messages:

            branch = "agent-landing-page"
            #for demo run this
            #branch = f"agent-landing-page-{int(time.time())}"
            print("Engineer Agent received task")
            html_prompt = "Create a simple HTML landing page for TaskTriage..."

            # 🔥 CREATE GITHUB ISSUE

            issue_res = requests.post(
                f"https://api.github.com/repos/{REPO}/issues",
                headers=HEADERS,
                json={
                    "title": "Initial landing page",
                    "body": "Landing page generated by Engineer Agent"
                }
            )

            issue_url = issue_res.json().get("html_url")

            print(f"📝 Issue created: {issue_url}")


            ref_res = requests.get(
                f"https://api.github.com/repos/{REPO}/git/ref/heads/main",
                headers=HEADERS
            )

            base_sha = ref_res.json()["object"]["sha"]

            # create new branch
            branch_res = requests.post(
                f"https://api.github.com/repos/{REPO}/git/refs",
                headers=HEADERS,
                json={
                    "ref": f"refs/heads/{branch}",
                    "sha": base_sha
                }
            )

            if branch_res.status_code == 201:
                print(f"[Engineer] Created branch: {branch}")
            else:
                print(f"[Engineer] Branch may already exist, continuing...")

            html_content = call_llm(html_prompt)
            import re

            match = re.search(r"<!DOCTYPE html>.*</html>", html_content, re.DOTALL)

            if match:
                html_content = match.group()
            else:
                print("⚠️ Could not extract clean HTML, using raw output")
            content = base64.b64encode(html_content.encode()).decode()

                        # GET from branch
            get_url = f"https://api.github.com/repos/{REPO}/contents/index.html?ref={branch}"

            # PUT to repo (no ref here)
            put_url = f"https://api.github.com/repos/{REPO}/contents/index.html"
                        
            # --- NEW: Check if file exists to get SHA ---
            get_res = requests.get(get_url, headers=HEADERS)
            sha = None
            if get_res.status_code == 200:
                sha = get_res.json().get("sha")

            data = {
                "message": "Add landing page",
                "content": content,
                "branch": branch
            }
            if sha:
                data["sha"] = sha  # Required for updates!
            # --------------------------------------------

            response = requests.put(put_url, headers=HEADERS, json=data)
            if response.status_code in [200, 201]:
                print("✅ Code committed to GitHub")

                # 🔥 CREATE PULL REQUEST

                pr_res = requests.post(
                    f"https://api.github.com/repos/{REPO}/pulls",
                    headers=HEADERS,
                    json={
                        "title": "Add TaskTriage Landing Page",
                        "head": branch,
                        "base": "main",
                        "body": "Generated by Engineer Agent"
                    }
                )

                pr_url = pr_res.json().get("html_url")

                print(f"🚀 PR created: {pr_url}")
            else:
                print("❌ GitHub error:", response.json())